name: Checks

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Output installed packages
        run: |
            pip freeze --all

      - name: flake8
        run: flake8 .      
